/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccueilRouteImport } from './routes/accueil'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as MessagerieRouteImport } from './routes/messagerie'
import { Route as NavigateursRouteImport } from './routes/navigateurs'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as ApiPublicProxyRouteImport } from './routes/api/public/proxy'
import { Route as ApiPublicPxSplatRouteImport } from './routes/api/public/px/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccueilRoute = AccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagerieRoute = MessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateursRoute = NavigateursRouteImport.update({
  id: '/navigateurs',
  path: '/navigateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyRoute = ApiPublicProxyRouteImport.update({
  id: '/api/public/proxy',
  path: '/api/public/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPxSplatRoute = ApiPublicPxSplatRouteImport.update({
  id: '/api/public/px/$',
  path: '/api/public/px/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/emails': typeof EmailsRoute
  '/messagerie': typeof MessagerieRoute
  '/navigateurs': typeof NavigateursRoute
  '/produits': typeof ProduitsRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/px/$': typeof ApiPublicPxSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/emails': typeof EmailsRoute
  '/messagerie': typeof MessagerieRoute
  '/navigateurs': typeof NavigateursRoute
  '/produits': typeof ProduitsRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/px/$': typeof ApiPublicPxSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/emails': typeof EmailsRoute
  '/messagerie': typeof MessagerieRoute
  '/navigateurs': typeof NavigateursRoute
  '/produits': typeof ProduitsRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/px/$': typeof ApiPublicPxSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accueil'
    | '/emails'
    | '/messagerie'
    | '/navigateurs'
    | '/produits'
    | '/api/public/proxy'
    | '/api/public/px/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accueil'
    | '/emails'
    | '/messagerie'
    | '/navigateurs'
    | '/produits'
    | '/api/public/proxy'
    | '/api/public/px/$'
  id:
    | '__root__'
    | '/'
    | '/accueil'
    | '/emails'
    | '/messagerie'
    | '/navigateurs'
    | '/produits'
    | '/api/public/proxy'
    | '/api/public/px/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccueilRoute: typeof AccueilRoute
  EmailsRoute: typeof EmailsRoute
  MessagerieRoute: typeof MessagerieRoute
  NavigateursRoute: typeof NavigateursRoute
  ProduitsRoute: typeof ProduitsRoute
  ApiPublicProxyRoute: typeof ApiPublicProxyRoute
  ApiPublicPxSplatRoute: typeof ApiPublicPxSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accueil': {
      id: '/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messagerie': {
      id: '/messagerie'
      path: '/messagerie'
      fullPath: '/messagerie'
      preLoaderRoute: typeof MessagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigateurs': {
      id: '/navigateurs'
      path: '/navigateurs'
      fullPath: '/navigateurs'
      preLoaderRoute: typeof NavigateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy': {
      id: '/api/public/proxy'
      path: '/api/public/proxy'
      fullPath: '/api/public/proxy'
      preLoaderRoute: typeof ApiPublicProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/px/$': {
      id: '/api/public/px/$'
      path: '/api/public/px/$'
      fullPath: '/api/public/px/$'
      preLoaderRoute: typeof ApiPublicPxSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccueilRoute: AccueilRoute,
  EmailsRoute: EmailsRoute,
  MessagerieRoute: MessagerieRoute,
  NavigateursRoute: NavigateursRoute,
  ProduitsRoute: ProduitsRoute,
  ApiPublicProxyRoute: ApiPublicProxyRoute,
  ApiPublicPxSplatRoute: ApiPublicPxSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
